version: '3'
services:
  metaprime_db:
    image: postgres:14
    restart: always
    ports:
      - "5484:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metaprime_db